version: '3.7'
services: 
  delivery-much:
    image: node:14.15.3-alpine
    working_dir: "/usr/current/app"
    command: "npm run dev"
    env_file: .env
    volumes: 
      - .:/usr/current/app:rw
      - ./node_modules:/usr/current/app/node_modules:cached
    ports: [ "3000:3000", "9229:9229"]
